version: '3.9'

services:
  dbPostgres:
    image: postgres:10
    restart: always
    ports:
      - 5432:5432
    environment: 
      POSTGRES_USER: root
      POSTGRES_PASSWORD: docker 
      POSTGRES_DB: mydb
    volumes:
      - db-data:/var/lib/postgresql
    networks:
      - mynet

  django:
    build: .
    command: ./run_web.sh
    ports:
      - 80:8080
    depends_on:
      - dbPostgres
    networks:
      - mynet
    



networks:
  mynet:

volumes:
  db-data: 
